# Generated by Django 5.1.4 on 2025-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_app', '0002_remove_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
